spring.application.name=climbing-sala
spring.datasource.url=jdbc:postgresql://localhost:5432/penjacka_sala
spring.datasource.username=hristinaamarjanovic
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

